language: go
go:
  - 1.5
  - 1.6
  - tip
install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/github.com/harvey-os/ninep"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/github.com/harvey-os/ninep"
  - go get -v -t -d github.com/harvey-os/ninep/...
script:
  - go test github.com/harvey-os/ninep/...